import './globals.css'
import { inter } from '@/app/ui/fonts'

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'

import TopBar from '@/components/TopBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AppRouterCacheProvider>
          <TopBar />
          <main className="h-[350vh]">{children}</main>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
