import { Providers } from './context/provider'

import TopBar from '@/components/TopBar'
import BackgroundVideo from '@/components/BackgroundVideo'
import { inter, nunitoSans } from '@/ui/fonts'

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${nunitoSans.variable}`}>
        <Providers>
          <TopBar />
          <main>{children}</main>
          <BackgroundVideo />
        </Providers>
      </body>
    </html>
  )
}
