name: Deploy Production Workflow

on:
  push:
    branches:
      - main

jobs:
  deployS3:
    name: DeployS3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.20.2
        
      - run: yarn install
        working-directory: ./app
      
      - run: yarn build
        working-directory: ./app
      
      - run: pwd
      
      - run: ls -la

      - name: Sync to S3
        uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync ./out s3://blockify-landing-page
        working-directory: ./app
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
