name: Deploy Production Workflow

on:
  push:
    branches:
      - main

jobs:
  deployS3:
    name: DeployS3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.20.2
        
      - run: yarn install
      
      - run: yarn build
        env: 
          NEXT_PUBLIC_MAIL_SERVICE_ID: ${{ vars.NEXT_PUBLIC_MAIL_SERVICE_ID}}
          NEXT_PUBLIC_MAIL_TEMPLATE_ID: ${{ vars.NEXT_PUBLIC_MAIL_TEMPLATE_ID}}
          NEXT_PUBLIC_MAIL_PUBLIC_KEY: ${{ vars.NEXT_PUBLIC_MAIL_PUBLIC_KEY}}
      
      - run: echo ${{ vars.NEXT_PUBLIC_MAIL_SERVICE_ID}}
      
      - run: ls -la

      - run: pwd
      
      - name: Deploy to S3
        #run: aws s3 sync ./out s3://blockify-landing-page
        run: sh deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
